import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const products = [
  // MEN'S PRODUCTS (12)
  {
    title: "Nike Air Max 270",
    description: "Experience comfort like never before with the Nike Air Max 270. Featuring the first-ever 270-degree Air unit, these shoes provide exceptional cushioning for all-day wear.",
    price: 150.00,
    comparePrice: 180.00,
    image: "/images/product-shoe.jpg",
    category: "Men",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 50,
    rating: 4.5,
    reviewCount: 128,
    featured: true,
  },
  {
    title: "Nike Air Force 1 '07",
    description: "The radiance lives on in the Nike Air Force 1 '07, the basketball original that puts a fresh spin on what you know best: crisp leather, bold colors and the perfect amount of flash to make you shine.",
    price: 110.00,
    comparePrice: null,
    image: "/images/product-shoe.jpg",
    category: "Men",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 75,
    rating: 4.7,
    reviewCount: 256,
    featured: true,
  },
  {
    title: "Nike React Infinity Run Flyknit",
    description: "The Nike React Infinity Run Flyknit is designed to keep you running. A cropped sock liner works in tandem with a supportive collar to provide softness and breathability where you need it.",
    price: 160.00,
    comparePrice: 200.00,
    image: "/images/product-shoe.jpg",
    category: "Men",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 40,
    rating: 4.6,
    reviewCount: 89,
    featured: false,
  },
  {
    title: "Nike Zoom Pegasus 38",
    description: "The Nike Zoom Pegasus 38 continues to put a spring in your step, just like its predecessor. Updated with a breathable mesh upper, it lets your foot flex and stretch.",
    price: 120.00,
    comparePrice: null,
    image: "/images/product-shoe.jpg",
    category: "Men",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 60,
    rating: 4.8,
    reviewCount: 312,
    featured: true,
  },
  {
    title: "Nike Air Zoom Structure 24",
    description: "Keep your run going with the Nike Air Zoom Structure 24. This everyday running shoe is designed to keep you supported with stable cushioning.",
    price: 130.00,
    comparePrice: 150.00,
    image: "/images/product-shoe.jpg",
    category: "Men",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 45,
    rating: 4.4,
    reviewCount: 67,
    featured: false,
  },
  {
    title: "Nike Metcon 7",
    description: "The Nike Metcon 7 is the gold standard for weight training. It brings stability and durability to your workout with a flat, wide heel and light-weight mesh.",
    price: 130.00,
    comparePrice: null,
    image: "/images/product-shoe.jpg",
    category: "Men",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 35,
    rating: 4.6,
    reviewCount: 94,
    featured: true,
  },
  {
    title: "Nike Dri-FIT Men's Training T-Shirt",
    description: "The Nike Dri-FIT Men's Training T-Shirt delivers breathable comfort and sweat-wicking technology to keep you dry and comfortable during your workout.",
    price: 35.00,
    comparePrice: 45.00,
    image: "/images/product-shoe.jpg",
    category: "Men",
    subcategory: "Apparel",
    brand: "Nike",
    stock: 100,
    rating: 4.3,
    reviewCount: 156,
    featured: false,
  },
  {
    title: "Nike Men's Sportswear Club Hoodie",
    description: "The Nike Sportswear Club Hoodie is made from a cotton-blend fabric and has an oversize fit for a comfortable, relaxed feel.",
    price: 65.00,
    comparePrice: null,
    image: "/images/product-shoe.jpg",
    category: "Men",
    subcategory: "Apparel",
    brand: "Nike",
    stock: 80,
    rating: 4.5,
    reviewCount: 203,
    featured: false,
  },
  {
    title: "Nike Pro Men's 3-Inch Shorts",
    description: "The Nike Pro 3-Inch Shorts combine a slim fit and high-stretch fabric to help you move freely and comfortably through your workout.",
    price: 35.00,
    comparePrice: 45.00,
    image: "/images/product-shoe.jpg",
    category: "Men",
    subcategory: "Apparel",
    brand: "Nike",
    stock: 90,
    rating: 4.4,
    reviewCount: 178,
    featured: false,
  },
  {
    title: "Nike Air Max 90",
    description: "The Nike Air Max 90 stays true to its roots with the iconic Waffle sole, stitched overlays and classic TPU accents.",
    price: 130.00,
    comparePrice: 150.00,
    image: "/images/product-shoe.jpg",
    category: "Men",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 55,
    rating: 4.7,
    reviewCount: 289,
    featured: true,
  },
  {
    title: "Nike SB Zoom Blazer Mid",
    description: "The Nike SB Zoom Blazer Mid is a skate-ready version of a classic. With a Zoom Air unit in the heel and padded collar, it delivers comfort and impact protection.",
    price: 105.00,
    comparePrice: null,
    image: "/images/product-shoe.jpg",
    category: "Men",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 40,
    rating: 4.5,
    reviewCount: 112,
    featured: false,
  },
  {
    title: "Nike Air Jordan 1 Retro High",
    description: "The Air Jordan 1 Retro High brings back the original look of Michael Jordan's first signature shoe with premium leather and classic color blocking.",
    price: 180.00,
    comparePrice: 200.00,
    image: "/images/product-shoe.jpg",
    category: "Men",
    subcategory: "Shoes",
    brand: "Jordan",
    stock: 30,
    rating: 4.9,
    reviewCount: 456,
    featured: true,
  },

  // WOMEN'S PRODUCTS (12)
  {
    title: "Nike Air Max 270 React",
    description: "The Nike Air Max 270 React combines the comfort of a large Air unit with the springy responsiveness of Nike React foam for all-day comfort.",
    price: 150.00,
    comparePrice: 180.00,
    image: "/images/product-shoe.jpg",
    category: "Women",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 45,
    rating: 4.6,
    reviewCount: 134,
    featured: true,
  },
  {
    title: "Nike Air Zoom Pegasus 38 Women's",
    description: "The Nike Air Zoom Pegasus 38 continues to put a spring in your step. Updated with a breathable mesh upper, it lets your foot flex and stretch.",
    price: 120.00,
    comparePrice: null,
    image: "/images/product-shoe.jpg",
    category: "Women",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 65,
    rating: 4.8,
    reviewCount: 267,
    featured: true,
  },
  {
    title: "Nike Revolution 6 Women's",
    description: "The Nike Revolution 6 provides comfortable support with soft foam, breathable knit fabric, and a comfortable collar that wraps around your ankle.",
    price: 65.00,
    comparePrice: 75.00,
    image: "/images/product-shoe.jpg",
    category: "Women",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 80,
    rating: 4.4,
    reviewCount: 189,
    featured: false,
  },
  {
    title: "Nike Free RN 2021 Women's",
    description: "The Nike Free RN 2021 gives you the feeling of running barefoot. The updated sole has a wider heel, allowing for a more stable landing.",
    price: 100.00,
    comparePrice: null,
    image: "/images/product-shoe.jpg",
    category: "Women",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 50,
    rating: 4.5,
    reviewCount: 98,
    featured: false,
  },
  {
    title: "Nike Downshifter 11 Women's",
    description: "The Nike Downshifter 11 offers cushioned comfort and breathable support. Its updated design includes a more breathable upper and softer foam.",
    price: 70.00,
    comparePrice: 85.00,
    image: "/images/product-shoe.jpg",
    category: "Women",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 75,
    rating: 4.3,
    reviewCount: 145,
    featured: false,
  },
  {
    title: "Nike Metcon 7 Women's",
    description: "The Nike Metcon 7 is the gold standard for weight training. It brings stability and durability to your workout with a flat, wide heel.",
    price: 130.00,
    comparePrice: null,
    image: "/images/product-shoe.jpg",
    category: "Women",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 40,
    rating: 4.7,
    reviewCount: 87,
    featured: true,
  },
  {
    title: "Nike Dri-FIT Women's Training Tank Top",
    description: "The Nike Dri-FIT Tank Top combines sweat-wicking technology with a sleek, minimalist design to help you stay cool and focused.",
    price: 30.00,
    comparePrice: 40.00,
    image: "/images/product-shoe.jpg",
    category: "Women",
    subcategory: "Apparel",
    brand: "Nike",
    stock: 95,
    rating: 4.4,
    reviewCount: 167,
    featured: false,
  },
  {
    title: "Nike Women's Sportswear Club Hoodie",
    description: "The Nike Sportswear Club Hoodie is made from a cotton-blend fabric and has an oversize fit for a comfortable, relaxed feel.",
    price: 65.00,
    comparePrice: null,
    image: "/images/product-shoe.jpg",
    category: "Women",
    subcategory: "Apparel",
    brand: "Nike",
    stock: 70,
    rating: 4.6,
    reviewCount: 221,
    featured: false,
  },
  {
    title: "Nike Pro Women's Mid-Rise Tights",
    description: "The Nike Pro Tights hug your body from hip to hem to help you feel secure and supported through your workout.",
    price: 55.00,
    comparePrice: 70.00,
    image: "/images/product-shoe.jpg",
    category: "Women",
    subcategory: "Apparel",
    brand: "Nike",
    stock: 85,
    rating: 4.5,
    reviewCount: 198,
    featured: false,
  },
  {
    title: "Nike Air Max 90 Women's",
    description: "The Nike Air Max 90 stays true to its roots with the iconic Waffle sole, stitched overlays and classic TPU accents.",
    price: 130.00,
    comparePrice: 150.00,
    image: "/images/product-shoe.jpg",
    category: "Women",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 50,
    rating: 4.7,
    reviewCount: 234,
    featured: true,
  },
  {
    title: "Nike Blazer Mid '77 Vintage Women's",
    description: "The Nike Blazer Mid '77 Vintage delivers a hoops look that's full of history. With vintage colors and plush foam, it brings retro style.",
    price: 105.00,
    comparePrice: null,
    image: "/images/product-shoe.jpg",
    category: "Women",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 45,
    rating: 4.6,
    reviewCount: 145,
    featured: false,
  },
  {
    title: "Nike Court Legacy Women's",
    description: "The Nike Court Legacy combines the heritage of court style with everyday comfort. Its padded collar feels soft and cushioned.",
    price: 75.00,
    comparePrice: 90.00,
    image: "/images/product-shoe.jpg",
    category: "Women",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 60,
    rating: 4.4,
    reviewCount: 112,
    featured: false,
  },

  // KIDS' PRODUCTS (10)
  {
    title: "Nike Air Max 90 Big Kids'",
    description: "The Nike Air Max 90 brings the old-school look with a modern twist. With a visible Air unit and Waffle outsole, it delivers classic comfort.",
    price: 85.00,
    comparePrice: 100.00,
    image: "/images/product-shoe.jpg",
    category: "Kids",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 60,
    rating: 4.7,
    reviewCount: 89,
    featured: true,
  },
  {
    title: "Nike Air Force 1 '07 Big Kids'",
    description: "The Nike Air Force 1 '07 features classic hoops style with an oversized Air sole for cushioning and a padded collar for comfort.",
    price: 75.00,
    comparePrice: null,
    image: "/images/product-shoe.jpg",
    category: "Kids",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 70,
    rating: 4.8,
    reviewCount: 145,
    featured: true,
  },
  {
    title: "Nike Revolution 6 Big Kids'",
    description: "The Nike Revolution 6 provides comfortable support with soft foam, breathable knit fabric, and a comfortable collar.",
    price: 55.00,
    comparePrice: 65.00,
    image: "/images/product-shoe.jpg",
    category: "Kids",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 80,
    rating: 4.5,
    reviewCount: 98,
    featured: false,
  },
  {
    title: "Nike Flex Runner 3 Big Kids'",
    description: "The Nike Flex Runner 3 gives your little one an easy-on, easy-off shoe that's lightweight, comfortable, and ready to play.",
    price: 50.00,
    comparePrice: 60.00,
    image: "/images/product-shoe.jpg",
    category: "Kids",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 75,
    rating: 4.6,
    reviewCount: 112,
    featured: false,
  },
  {
    title: "Nike Star Runner 3 Little Kids'",
    description: "The Nike Star Runner 3 gives your little one comfort for their daily adventures. The hook-and-loop strap makes it easy to get on and off.",
    price: 45.00,
    comparePrice: null,
    image: "/images/product-shoe.jpg",
    category: "Kids",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 65,
    rating: 4.7,
    reviewCount: 134,
    featured: false,
  },
  {
    title: "Nike Sunray Protect 2 Big Kids'",
    description: "The Nike Sunray Protect 2 is designed for summer fun with quick-drying fabric, a soft sole, and extra coverage for toes and heels.",
    price: 40.00,
    comparePrice: 50.00,
    image: "/images/product-shoe.jpg",
    category: "Kids",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 70,
    rating: 4.5,
    reviewCount: 87,
    featured: false,
  },
  {
    title: "Nike Dri-FIT Big Kids' Training T-Shirt",
    description: "The Nike Dri-FIT Training T-Shirt delivers breathable comfort and sweat-wicking technology to keep kids dry and comfortable.",
    price: 25.00,
    comparePrice: 30.00,
    image: "/images/product-shoe.jpg",
    category: "Kids",
    subcategory: "Apparel",
    brand: "Nike",
    stock: 90,
    rating: 4.4,
    reviewCount: 156,
    featured: false,
  },
  {
    title: "Nike Sportswear Big Kids' Club Hoodie",
    description: "The Nike Sportswear Club Hoodie is made from a cotton-blend fabric and has an oversize fit for a comfortable, relaxed feel.",
    price: 45.00,
    comparePrice: null,
    image: "/images/product-shoe.jpg",
    category: "Kids",
    subcategory: "Apparel",
    brand: "Nike",
    stock: 75,
    rating: 4.6,
    reviewCount: 189,
    featured: false,
  },
  {
    title: "Nike Air Max 270 Big Kids'",
    description: "The Nike Air Max 270 Big Kids' shoe brings the biggest Air unit to date to the feet of the next generation of athletes.",
    price: 90.00,
    comparePrice: 110.00,
    image: "/images/product-shoe.jpg",
    category: "Kids",
    subcategory: "Shoes",
    brand: "Nike",
    stock: 55,
    rating: 4.7,
    reviewCount: 123,
    featured: true,
  },
  {
    title: "Nike Jordan 1 Mid Big Kids'",
    description: "The Air Jordan 1 Mid captures the essence of the original and updates it with comfortable cushioning and flexible traction.",
    price: 85.00,
    comparePrice: null,
    image: "/images/product-shoe.jpg",
    category: "Kids",
    subcategory: "Shoes",
    brand: "Jordan",
    stock: 50,
    rating: 4.8,
    reviewCount: 178,
    featured: true,
  },
];

async function main() {
  console.log('Seeding database...');

  // Clear existing products
  await prisma.product.deleteMany({});

  // Create products
  for (const product of products) {
    await prisma.product.create({
      data: product,
    });
    console.log(`Created product: ${product.title}`);
  }

  console.log(`Seeded ${products.length} products successfully!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
